ERROR - 2022-12-11 07:24:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' in /var/www/html/ci/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/ci/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /var/www/html/ci/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/ci/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/ci/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/ci/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/ci/system/BaseModel.php(585): CodeIgniter\Model->doFindAll()
#6 /var/www/html/ci/app/Controllers/UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/ci/system/CodeIgniter.php(927): App\Controllers\UserCrud->index()
#8 /var/www/html/ci/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#9 /var/www/html/ci/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#10 /var/www/html/ci/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /var/www/html/ci/system/Commands/Server/rewrite.php(46): require_once('...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' in /var/www/html/ci/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/ci/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/ci/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/ci/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/ci/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/ci/system/BaseModel.php(585): CodeIgniter\Model->doFindAll()
#5 /var/www/html/ci/app/Controllers/UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/ci/system/CodeIgniter.php(927): App\Controllers\UserCrud->index()
#7 /var/www/html/ci/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#8 /var/www/html/ci/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#9 /var/www/html/ci/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 /var/www/html/ci/system/Commands/Server/rewrite.php(46): require_once('...')
#11 {main}
CRITICAL - 2022-12-11 07:24:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost'
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll()
 5 APPPATH/Controllers/UserCrud.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\UserCrud->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(46): require_once('FCPATH/index.php')
